### ISSUE TITLE
OpenAIError: missing role for choice 0 when using anthropic:claude-3-5-sonnet-*

### ISSUE THREAD

**Issue by yharaskrik** [LangbaseInc/BaseAI#105]
### Description

I am trying to use the anthropic:claude-3-5-sonnet-* models for my pipe but when I run it, i get 

```
Error: OpenAIError: missing role for choice 0
    at <anonymous> (/Users/jaybell/WebstormProjects/chat-mtg/node_modules/@baseai/core/node_modules/openai/src/lib/ChatCompletionStream.ts:624:17)
    at Array.map (<anonymous>)
    at finalizeChatCompletion (/Users/jaybell/WebstormProjects/chat-mtg/node_modules/@baseai/core/node_modules/openai/src/lib/ChatCompletionStream.ts:615:22)
    at ChatCompletionStream._ChatCompletionStream_endRequest (/Users/jaybell/WebstormProjects/chat-mtg/node_modules/@baseai/core/node_modules/openai/src/lib/ChatCompletionStream.ts:365:12)
    at ChatCompletionStream._fromReadableStream (/Users/jaybell/WebstormProjects/chat-mtg/node_modules/@baseai/core/node_modules/openai/src/lib/ChatCompletionStream.ts:420:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Works fine if I switch it to an openai model (without any code changes). My 2 messages are a system and a user prompt (taken from the learn baseai guide).

I can see in the logging that the roles are there so I suspect this is an interopt issue between the openai sdk baseai is using and the anthropic api.

**Comment by msaaddev** [comment]
Thanks for reporting this @yharaskrik! We are shipping fix for it today.

**Comment by ahmadawais** [comment]
Can you please share the reproducible code? Like your pipe so we can easily test this?

@msaaddev please check.

**Comment by msaaddev** [comment]
> Can you please share the reproducible code? Like your pipe so we can easily test this?
> 
> @msaaddev please check.

@ahmadawais I already know what is causing this. I will ship a fix for it today.

**Comment by msaaddev** [comment]
@yharaskrik I just shipped a new version with the fix. Can you please update BaseAI `baseai/core` and `baseai` package to the latest version and test again?

**Comment by ahmadawais** [comment]
@msaaddev please mention the new version number so we are sure @latest is installing the correct one.

**Comment by msaaddev** [comment]
> @msaaddev please mention the new version number so we are sure @latest is installing the correct one.

Updated.

**Comment by ahmadawais** [comment]
Assume this is now solved so closing the issue.
